import * as React from 'react';
import * as RawDuo from '@duo-icons/react';
import type { DuoIconProps } from './DuoIcons';

export * from './TrashDuo';
export * from './DuoIcons';

export type DuoIconComponent = React.FC<DuoIconProps>;

export const AddCircle = RawDuo.AddCircle as unknown as DuoIconComponent;
export const Plus = AddCircle;
export const PlusDuo = AddCircle;
export const Award = RawDuo.Award as unknown as DuoIconComponent;
export const Bell = RawDuo.Bell as unknown as DuoIconComponent;
export const BellBadge = RawDuo.BellBadge as unknown as DuoIconComponent;
export const Book = RawDuo.Book as unknown as DuoIconComponent;
export const Book2 = RawDuo.Book2 as unknown as DuoIconComponent;
export const Book3 = RawDuo.Book3 as unknown as DuoIconComponent;
export const Bookmark = RawDuo.Bookmark as unknown as DuoIconComponent;
export const Briefcase = RawDuo.Briefcase as unknown as DuoIconComponent;
export const Building = RawDuo.Building as unknown as DuoIconComponent;
export const Calendar = RawDuo.Calendar as unknown as DuoIconComponent;
export const Certificate = RawDuo.Certificate as unknown as DuoIconComponent;
export const ChartPie = RawDuo.ChartPie as unknown as DuoIconComponent;
export const CheckCircle = RawDuo.CheckCircle as unknown as DuoIconComponent;
export const Chip = RawDuo.Chip as unknown as DuoIconComponent;
export const Clipboard = RawDuo.Clipboard as unknown as DuoIconComponent;
export const Clock = RawDuo.Clock as unknown as DuoIconComponent;
export const CreditCard = RawDuo.CreditCard as unknown as DuoIconComponent;
export const Dashboard = RawDuo.Dashboard as unknown as DuoIconComponent;
export const File = RawDuo.File as unknown as DuoIconComponent;
export const DuoFile = File;
export const FolderOpen = RawDuo.FolderOpen as unknown as DuoIconComponent;
export const FolderUpload = RawDuo.FolderUpload as unknown as DuoIconComponent;
export const IdCard = RawDuo.IdCard as unknown as DuoIconComponent;
export const Info = RawDuo.Info as unknown as DuoIconComponent;
export const Location = RawDuo.Location as unknown as DuoIconComponent;
export const Menu = RawDuo.Menu as unknown as DuoIconComponent;
export const Message = RawDuo.Message as unknown as DuoIconComponent;
export const Message2 = RawDuo.Message2 as unknown as DuoIconComponent;
export const Message3 = RawDuo.Message3 as unknown as DuoIconComponent;
export const Moon2 = RawDuo.Moon2 as unknown as DuoIconComponent;
export const MoonStars = RawDuo.MoonStars as unknown as DuoIconComponent;
export const Palette = RawDuo.Palette as unknown as DuoIconComponent;
export const Rocket = RawDuo.Rocket as unknown as DuoIconComponent;
export const Settings = RawDuo.Settings as unknown as DuoIconComponent;
export const ShoppingBag = RawDuo.ShoppingBag as unknown as DuoIconComponent;
export const Sun = RawDuo.Sun as unknown as DuoIconComponent;
export const Target = RawDuo.Target as unknown as DuoIconComponent;
export const UploadFile = RawDuo.UploadFile as unknown as DuoIconComponent;
export const User = RawDuo.User as unknown as DuoIconComponent;
export const UserCard = RawDuo.UserCard as unknown as DuoIconComponent;
export const World = RawDuo.World as unknown as DuoIconComponent;
